# Tomcat
server:
    tomcat:
        max-threads: 1000
        min-spare-threads: 30
    port: 8088
# Mybatis配置
mybatis:
    mapperLocations: classpath*:mapper/**/*.xml,classpath:bizmybatis/**/*.xml
    configLocation: classpath:mybatis.xml

#logging.level.io.renren=DEBUG

